### ISSUE TITLE
能否借用主题呢？

### ISSUE THREAD

**Issue by BruceZhaoR** [zonxin/zonxin.github.io#1]
博主您好！我是偶然间在sf上面看到您的个人博客网址。我的[博客](http://bzrlc.github.io)是这个主题最原始的版本，看到您做了一些定制，我觉得非常棒，能否借鉴过去呢？如果你同意的话，我会在底部注明来源，并指向您的博客地址。如果您不同意的话，我会另寻其他模板。

**Comment by zonxin** [comment]
可以呀，只是我的也是自己瞎写的，不是专业人士设计的。
